import { clerkBootstrap, type ClerkUiConfig } from "./clerk-ui";
import { WORKSPACE_CSS } from "./workspace-theme";
import { WORKSPACE_JS } from "./workspace-client";

const esc = (s: string) => s.replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[ch]!);
export interface WorkspaceOptions { hosted?: boolean; authConfigured?: boolean; authProvider?: "google" | "clerk"; clerk?: ClerkUiConfig; nonce?: string; publicLanding?: boolean; apiUrl?: string; signInPath?: string; assets?: Record<string, string> }
/** Opt-in next-release interface. Authentication is identical to the legacy dashboard. */
export function workspaceHtml(name: string, options: WorkspaceOptions = {}): string {
  const logo = options.assets?.["assets/hitchhike-bus-logo.png"];
  const returnTo = options.clerk?.returnTo === "/app-next" ? "/app-next" : "/app";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><meta name="theme-color" content="#ffffff"><meta name="robots" content="noindex"><title>Your agents · ${esc(name)}</title><style>${WORKSPACE_CSS}
.main:focus{outline:none}.provider-option{text-decoration:none}.agent-icon img{width:27px;height:27px;object-fit:contain}.agent-icon.code img{border-radius:5px}.page-error{margin:20px 0}.readiness{margin-bottom:24px}.readiness .milestone:last-child{border:0}.stack{display:grid;gap:12px}.inline-fields{display:grid;grid-template-columns:1fr 1fr;gap:18px}.form-section:first-child{margin-top:0}.form-section .check-row{max-width:650px}.danger{color:var(--danger)}.plain-list{padding-left:22px;color:var(--muted);font-size:14px}.plain-list li{margin-bottom:9px}.context-text{white-space:pre-wrap;overflow-wrap:anywhere}.navigation-error{padding:16px 22px;background:#fff6f4;color:var(--danger);font-size:14px}.loading-title{min-height:60px}.welcome-note{padding:24px 0 8px;border-top:1px solid var(--rule)}.choice-group{border:0;padding:0;margin:0 0 24px}.choice-group legend{font-size:14px;font-weight:600;margin-bottom:10px}.hidden-link{position:absolute;top:-70px;left:20px;z-index:10;background:white;padding:12px 20px}.hidden-link:focus{top:10px}.empty-state .btn{margin-top:8px}.field-help{display:block;font-weight:400;color:var(--muted);font-size:13px;margin-top:6px}.config-notice{margin-top:16px}.toast{max-width:620px}.code-key{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}.collaborator-settings{padding:15px 0}.summary-description{white-space:pre-wrap;overflow-wrap:anywhere}.expired-code{color:var(--warning)}@media(max-width:700px){.inline-fields{grid-template-columns:1fr}.toast{width:max-content;max-width:calc(100% - 32px)}.sidebar-foot .settings-link{display:flex}.brand-fallback{font-size:23px;font-weight:700;letter-spacing:-.04em;text-decoration:none}.sidebar-foot .mobile-signout{display:none}.brand-fallback{font-size:22px}}
</style></head><body data-hosted="${options.hosted ? "true" : "false"}" data-auth-provider="${options.authProvider === "clerk" ? "clerk" : "google"}" data-api-url="${esc(options.apiUrl || "")}" data-assets="${esc(JSON.stringify(options.assets || {}))}"><a class="hidden-link" href="#main">Skip to content</a>
<div id="boot" class="gate" role="status"><div class="skeleton"></div><div class="skeleton short"></div><p class="muted">Opening your workspace…</p></div>
<section id="gate" class="gate" hidden><a class="brand-fallback" href="/">${esc(name)}</a><h1>Your agents,<br>working together.</h1><p class="muted">Sign in to connect your assistants and keep their handoffs together.</p><p id="session-error" class="error-text" role="alert" hidden></p>${options.hosted ? `${options.authConfigured ? `<a class="btn" href="${options.signInPath === "/sign-in" ? "/sign-in?return_to=" + encodeURIComponent(returnTo) : "/auth/start"}">Sign in or create an account</a>` : `<p class="error-text">Sign-in is not configured for this deployment.</p>`}` : `<form id="gate-form"><div class="form-group"><label for="owner-key">Owner key</label><input id="owner-key" type="password" required autocomplete="current-password"></div><button class="btn" type="submit">Open workspace</button></form>`}</section>
<div id="workspace" class="shell" hidden><aside class="sidebar">${logo ? `<a class="brand" href="#/agents" aria-label="${esc(name)} home"><img src="${esc(logo)}" alt="${esc(name)}"></a>` : `<a class="brand-fallback" href="#/agents">${esc(name)}</a>`}<nav class="nav" aria-label="Main navigation"><a href="#/agents" id="agents-nav"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>Your agents</a><a href="#/activity" id="activity-nav"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h10M4 18h13"/></svg>Activity</a></nav><footer class="sidebar-foot"><a class="settings-link" href="#/settings" aria-label="Workspace settings"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1"/></svg><span>Workspace settings</span></a><button class="mobile-signout" id="sign-out">Sign out</button><div class="workspace-label"><strong>Your workspace</strong><span>Free beta</span></div></footer></aside><div><div id="network-error" class="navigation-error" role="status" hidden></div><main class="main" id="main" tabindex="-1"></main></div></div><div id="toast" class="toast" role="status" aria-live="polite" hidden></div><noscript><p class="gate">Enable JavaScript to use Hitchhike.</p></noscript>
${options.hosted && options.authProvider === "clerk" && options.clerk ? clerkBootstrap(options.clerk) : ""}<script${options.nonce ? ` nonce="${esc(options.nonce)}"` : ""}>${WORKSPACE_JS}</script></body></html>`;
}
